version: '2'
services:
  app:
    container_name: identity_man_sys
    image: identity_man_sys_image
    build: .
    networks:
      - main_network
    volumes:
      - .:/app/src
    ports:
      - 4000:4000
networks:
  main_network:
    driver: bridge